### ISSUE TITLE
Missing folder metadata view

### ISSUE THREAD

**Issue by kuldaraas** [magenta-aps/E-Ark-CMIS-Viewer#1]
The folder view should also allow for viewing the full metadata of the folder (similarly to what is possible for items/single files)

**Comment by iamfrank** [comment]
In develop branch (#4). Both folders and files have "info" icon buttons that toggle modal with metadata.

**Comment by kuldaraas** [comment]
The functionality is fine! Just the (i) icon is maybe not that intuitive.... If you can think about a better icon then change it, if not then it's fine.

**Comment by iamfrank** [comment]
Yeah, icons are always tricky.
@kuldaraas, you are welcome to take a look at the [list of available icons](https://design.google.com/icons/) and suggest one that makes more sense in your eyes.
Presently, I think the (!) is our best bet - save a text button called 'meta'

**Comment by kuldaraas** [comment]
Nope, can't really think of anything reasonable. Was thinking about the description icon https://design.google.com/icons/#ic_description but that's not much better either... So let's keep it as is visually, please just add "mouse over" text to explain the button "View full metadata".

**Comment by iamfrank** [comment]
The change is on it's way into the codebase. #8

**Comment by iamfrank** [comment]
@DarkStar1 , can we close this?

**Comment by kuldaraas** [comment]
Fine with me.

**Comment by DarkStar1** [comment]
Will close after the display of extension metadata

**Comment by DarkStar1** [comment]
The UI, for the extended properties tab, needs fixing.

**Comment by iamfrank** [comment]
Fixes to UI for extended properties are pushed to develop. The outputted properties still don't make sense, though.

**Comment by kuldaraas** [comment]
Tested -> works fine
