### ISSUE TITLE
Accidental double-click resulting in wrong folder visualisation

### ISSUE THREAD

**Issue by kuldaraas** [magenta-aps/E-Ark-CMIS-Viewer#10]
When unknowingly doing a double-click on a folder name the top folder hierarchy view shows two times the folder name. 
![image](https://cloud.githubusercontent.com/assets/1306341/19960829/e226aa60-a1b7-11e6-9153-551d56daec03.png)

**Comment by iamfrank** [comment]
A fix #12 is in develop branch now.

We stop the breadcrumb from being populated twice by resetting the folder contents so they disappear. This way you can't click the same item twice. It's not very elegant but it works.

**Comment by DarkStar1** [comment]
This is solved now
