### ISSUE TITLE
File not opening

### ISSUE THREAD

**Issue by kuldaraas** [magenta-aps/E-Ark-CMIS-Viewer#17]
Some files do not open in the CMIS Viewer (though some are). It seems that there are issues with non-standard characters in Estonian (ä, ö, õ, ü). 

Screenshots below
![view](https://cloud.githubusercontent.com/assets/1306341/20712060/35bb7b36-b64b-11e6-96ca-7a28d49d5b13.png)
![error](https://cloud.githubusercontent.com/assets/1306341/20712063/3818e6fc-b64b-11e6-873d-2f6a1fc4de85.png)

**Comment by DarkStar1** [comment]
This was an issue with the document names not being url encoded. It has been solved and is now working properly. Please test and confirm

**Comment by kuldaraas** [comment]
Tested -> works fine.
