### ISSUE TITLE
synchronise download and metadata view in file and folder view

### ISSUE THREAD

**Issue by kuldaraas** [magenta-aps/E-Ark-CMIS-Viewer#2]
The behaviour when clicking on the name of an item in the browsing view is not synchronised and intuitive: 
- when clicking on a folder it opens the folder; 
- when clicking on a file you can view the metadata. 
  
  As "open" and "metadata view" are required actions for all folders and files it should be synchronised so that clicking on an folder/file is executing one action and there is an icon for the other. 

I would recommend that clicking on the row always opens the folder or file; and there is a separate button for "view metadata".

**Comment by iamfrank** [comment]
Should be taken care of in latest development branch

**Comment by kuldaraas** [comment]
Is fine!
