### ISSUE TITLE
Missing button for getting back into the "Repository" view from Settings

### ISSUE THREAD

**Issue by kuldaraas** [magenta-aps/E-Ark-CMIS-Viewer#3]
When going to the settings (i.e. set up users or repository connection details) there is no button/link to get back to the repository view (i.e. browse and search).

**Comment by iamfrank** [comment]
Plenty of options for browsing back are now available in develop branch (#5)

**Comment by iamfrank** [comment]
Plenty of options for browsing back are now available in develop branch (#5)

**Comment by kuldaraas** [comment]
Can't see anything. Not deployed yet?
![no_button_back_to_browse](https://cloud.githubusercontent.com/assets/1306341/19359598/837f26d4-9183-11e6-90d5-7d2d977ddbf6.png)

**Comment by iamfrank** [comment]
Yeah, it's still only in the code repo. @DarkStar1 will deploy when possible.

**Comment by DarkStar1** [comment]
I have updated the repositories (front and backend) and tested the remote and the problem still persists

**Comment by kuldaraas** [comment]
In the current implementation there is a nice Back arrow available for getting out of the settings --> as far as I'm concerned you can close the issue.
